// Daily blessings from Pastor R.T. Owoseni — District Superintendent, C.A.C Salvation Centre, Ilorin.
// Curated from his public messages to the CAC Salvation District family; evergreen declarations only
// (event / date / time-specific posts were filtered out). One is shown per day on the Ilorin micro-site,
// rotated deterministically by day-of-year. 493 messages (~16 months before any repeat).

export const ILORIN_WORDS: string[] = [
  "May the Lord take hardship away from your life and comfort you on every side in Jesus name. HAVE A PROSPEROUS WEEK.",
  "Every demonic embargo placed on your success in life is removed in Jesus name. SHALOM!",
  "The same challenge that the enemy think will swallow you up shall be used by God for your progress in Jesus name. GOD BLESS YOU.",
  "All the powers waiting for your downfall and shame shall forever wait in vain in Jesus name. SHALOM.",
  "The Lord shall give you beauty in place of ashes and glory in place of shame. You shall Arise in glory. GOD BLESS YOU",
  "The Lord will give you rest from all your struggles and everything that is giving you unrest in Jesus name. GOD BLESS YOU",
  "Hear this word of prophecy, those who are looking for your defeat and downfall shall wait in vain forever in Jesus name. GOD BLESS YOU.",
  "The arrows of premature death sent to you and your family by the wicked shall return to the sender in Jesus name. GOD BLESS YOU.",
  "Your dreams will not be aborted. The Lord will not leave you until you are fulfilled in life in Jesus name GOD BLESS YOU",
  "May the Lord remember you for good. May you never labour in vain. SHALOM",
  "May the Lord overturn every negative pronouncement and judgement against you and your family in Jesus name. SHALOM!",
  "What kills others will not be able to kill you in Jesus name. You are exempted from destruction in Jesus name. GOD BLESS YOU",
  "Anything that is designed by the devil to draw your life backward shall be supernaturally converted to your advancement in Jesus name. GOD BLESS YOU",
  "The Almighty God will supernaturally heal all your open and secret wounds in your life in Jesus name. SHALOM!",
  "You will not just be a spectator in the gathering of successful people, but God will make you a centre of attraction in Jesus name. GOD BLESS YOU.",
  "May the Almighty God do something that will make you an enviable personality in your family and among your colleagues in Jesus name. GOD BLESS YOU",
  "Every demonic altar speaking hardship, delay and frustration into your life shall be burnt down in Jesus name. GOD BLESS YOU.",
  "The Lord will make it too difficult for the devil to hold your life captive. Your life will move forward in Jesus name. GOD BLESS YOU",
  "Everything that has made you shed tears before shall now make you laugh for Joy in Jesus name. HAPPY EASTER.",
  "Everything that is dead in your life shall come alive in Jesus name. The Lord is starting anew and afresh with you in Jesus name. GOD BLESS YOU.",
  "The shout of Joy and Celebration will never cease in your life in Jesus name. GOD BLESS YOU",
  "The better, bigger and greater thing that the Lord is preparing for you will surely come to manifestation in Jesus name. GOD BLESS YOU.",
  "May the Almighty God take over your battle and give you victory in Jesus name. GOD BLESS YOU.",
  "Every demonic altar speaking delay into your life is burnt down by the holy Ghost fire in Jesus name. GOD BLESS YOU.",
  "Voices that are saying your rising must be delayed or postponed are shut up forever in Jesus name. GOD BLESS YOU.",
  "May the Almighty God add more value to your life and make your entire life more attractive in Jesus name. GOD BLESS YOU",
  "May this day bring you and your family unending Joy and gladness in Jesus name. GOD BLESS YOU.",
  "The Lord God Almighty will turn your barren land to a fertile, fruitful and productive land in Jesus name. GOD BLESS YOU",
  "Everywhere you go people will favour you. You will grow in grace and favour in Jesus name. GOD BLESS YOU",
  "No matter the battle you are facing now, the Almighty God will fight for you in Jesus name. SHALOM",
  "The power of the Almighty God shall turn your challenges to miracles and testimonies in Jesus name GOD BLESS YOU.",
  "May the Lord remove every roadblock hindering your rising in Jesus name. GOD BLESS YOU.",
  "The God that made way for the Israelites at the Red Sea will make a way out of that challenge for you in Jesus name. SHALOM.",
  "Your dreams and visions in life shall surely find fulfilment in Jesus name. GOD BLESS YOU",
  "The power of the Almighty God shall lift you up and place you above every power threatening your life in Jesus name. GOD BLESS YOU.",
  "Because God can not be disgraced; therefore, everything put in place by the devil to disgrace you is set ablaze in Jesus name. SHALOM!",
  "May the good hand of the Almighty God never be withdrawn from your life. May you continue to enjoy Him on daily basis in Jesus name. GOD BLESS YOU",
  "May it please the Almighty God to complete every good thing he has started in your life, family and work in Jesus name. GOD BLESS YOU",
  "The agenda of the wicked will never find fulfilment over your life and family in Jesus name. SHALOM.",
  "Until you are divinely assisted, heaven will have no rest in Jesus name. GOD BLESS YOU.",
  "Every health challenge you are battling with will never take your life. Receive your healing in Jesus name. PEACE BE UNTO YOU.",
  "Every covenant of untimely death over you and your family members is cancelled in Jesus name. GOD BLESS YOU",
  "Things will continue to improve for the better for you. Your life will never go down in Jesus name. GOD BLESS YOU.",
  "The door of God's mercy will never be closed against you and your family in Jesus name. GOD BLESS YOU.",
  "Happy Father's Day to All our FATHERS in Salvation Centre. May God continue to bless you and give you the grace to live up to our responsibilities as father's in Jesus name. We shall live long to enjoy the labour of our hands in good health in Jesus name. HAPPY FATHER'S DAY!",
  "May the Lord remove every mountain, barrier, obstacle and opposition to your next level of glory in Jesus name. GOD BLESS YOU.",
  "Whatever that is making you crying shall from this moment bring you laughter in Jesus name. GOD BLESS YOU.",
  "I command by the Spirit of God, let every satanic umbrella covering your glory catch fire in Jesus name. GOD BLESS YOU.",
  "May the Lord rebuke dryness and poverty in your life and send His showers of blessing upon you in Jesus name. GOD BLESS YOU.",
  "Every stronghold of wickedness against you and your family shall collapse and come to an end in Jesus name. GOD BLESS YOU.",
  "The Almighty God shall turn your expectations to manifestation in Jesus name. GOD BLESS YOU.",
  "Every Satanic embargo placed on your life to limit your progress is removed by fire in Jesus name. HAVE A WONDERFUL WEEK.",
  "No matter how chronic and terrible your problem may be, the Almighty God will give you VICTORY over it in Jesus name. GOD BLESS YOU",
  "May the Lord take over all your battles from you and fight for you in Jesus name. REMAIN BLESSED.",
  "I rebuke every storm blowing against you and your family in Jesus name amen. GOD BLESS YOU",
  "Every curse of fruitless labour placed on your life is removed in Jesus name. Your labour shall be fruitful. HAVE A PROSPEROUS WEEK.",
  "May the Almighty God make you a terror to everything terrorising your life in Jesus name GOD BLESS YOU.",
  "May the Lord stretch forth his might hands and deliver you from every unfavorable situation in Jesus name. GOD BLESS YOU.",
  "Every negative word spoken into your life is cancelled in Jesus name. REMAIN BLESSED.",
  "May the Lord fulfill his promises in your life speedily in Jesus name No more delay. HAVE A PROSPEROUS WEEK",
  "May the Lord count you among the most FORTUNATE and FAVOURED ones on earth in Jesus name. SHALOM!",
  "The Lord will vindicate you from every satanic accusation and fight all your physical and spiritual battles for you in Jesus name. GOD BLESS YOU.",
  "The Lord of hosts will fight for you and give you victory over every challenge you are going through in Jesus name. SHALOM!",
  "May you find ALL that you need to live a fulfilled and meaningful life in Christ in Jesus name. GOD BLESS YOU.",
  "No matter how severe and chronic your challenges may be, the Lord will give you VICTORY in Jesus name. GOD BLESS YOU.",
  "May the Lord clothe you with His glory and grace. May He take away from your life anything that is shameful in Jesus name. PEACE BE UNTO YOU.",
  "Whatever you are going through shall lead to the glory of God in Jesus name. SHALOM!",
  "Every yoke of repeated failure assigned to destroy your life is broken in Jesus name. GOD BLESS YOU",
  "May this day be your day of great turnaround in Jesus name. GOD BLESS YOU",
  "May God take you from wilderness and move you to your promise land in Jesus name. GOD BLESS YOU.",
  "Every spring that is producing bitterness in your life is forever shut down in Jesus name. GOD BLESS YOU.",
  "Whatever the devil has concluded over your life and family is cancelled in Jesus name. GOD BLESS YOU.",
  "Where you have been mocked, rejected and disgraced, the Lord shall make you a celebrity in Jesus name. GOD BLESS YOU",
  "The Almighty God will surely intervene in the affairs of your life and you will surely have testimonies in Jesus name. GOD BLESS YOU",
  "As the Lord lives, you will laugh last and the devil will be put to shame in your life. GOD BLESS YOU.",
  "May the Lord give you wisdom to handle issues of your life wisely in Jesus name. GOD BLESS YOU",
  "The Covenant of God over your life will not fail. It will surely find fulfilment in Jesus name.. SHALOM!",
  "May the Lord turn your dry land to stream of waters and open your closed doors for overflowing blessings in Jesus name. SHALOM!",
  "May the Almighty God give you VICTORY over every challenge and obstacle that are on your way to progress in Jesus name. GOD BLESS YOU",
  "Everything that God created shall begin to work in your favour from this day in Jesus name. SHALOM!",
  "Every loophole the devil has created in your life to make you cry is blocked in Jesus name. PEACE BE UNTO YOU.",
  "Glorious things that you have never experienced shall begin to happen in your life in Jesus name. GOD BLESS YOU",
  "Every attempt from the devil to tamper with your JOY shall fail woefully in Jesus name. SHALOM.",
  "Every representative of Pharaoh or Goliath roaring or mocking your God shall be destroyed in Jesus name. GOD BLESS YOU",
  "Every door of good things that judgement has closed against you is declared open by the Mercy of God in Jesus name GOD BLESS YOU..",
  "By the grace of God your destiny will not be aborted in Jesus name. GOD BLESS YOU.",
  "Very soon the Lord will bring you out of your present challenges and lunch you into a better phase of your life in Jesus name. GOD BLESS YOU",
  "Every power challenging the authority of the Almighty God in your life is condemned and silenced forever in Jesus name. GOD BLESS YOU.",
  "May the Lord bless you with New IDEAS that will open the door of many opportunities to you in Jesus name. GOD BLESS YOU",
  "Every negative experience you have gone through in life will never come your way again in Jesus name. GOD BLESS YOU.",
  "May the Lord mercifully turn all your unpalatable situations to glorious testimonies in Jesus name. GOD BLESS YOU",
  "May your sun continue to shine and your glory continue to manifest in Jesus name. GOD BLESS YOU",
  "Every voice that is saying to you that you can't move forward is silenced forever in Jesus name. SHALOM!",
  "New things will never cease in your life, family and work in Jesus name. GOD BLESS YOU",
  "Where others are failing, you shall succeed in Jesus name. GOD BLESS YOU",
  "The Lord will defend you against all conspiracy and protect you from all arrows of the enemy in Jesus name. SHALOM!",
  "The Lord will deliver you from all conspiracies against your life and protect you from the arrows of the wicked in Jesus name.. GOD BLESS YOU.",
  "Anything standing between you and your breakthrough is removed by fire in Jesus name. GOD BLESS YOU.",
  "The Almighty God will attend to your case speedily and miraculously in Jesus name. GOD BLESS YOU.",
  "The Almighty God will silence every accuser of your glory in Jesus name. GOD BLESS YOU",
  "May your field of life remains evergreen and may your sky be full of water always in Jesus name. GOD BLESS YOU",
  "Your blood and that of your family members will not be used for any demonic sacrifice as the year is running to an end in Jesus name. GOD BLESS YOU.",
  "May the Lord compensate you in multiple folds any loss you have suffered in the past in Jesus name amen.. GOD BLESS YOU.",
  "May the Lord surround your life with destiny helpers in Jesus name. GOD BLESS YOU.",
  "May the Lord flood your life with end of the year blessings in Jesus name. GOD BLESS YOU",
  "You will never fall victim of any unfortunate occurrence as the year runs to an end in Jesus name. GOD BLESS YOU",
  "May the Lord give you and your family new identity that will bury all your past pains in Jesus name. GOD BLESS YOU.",
  "Divine Channel through which blessings will flow into your life is opened in Jesus name. GOD BLESS YOU.",
  "As the Lord lives, you will reign and rule over every challenge of your life in Jesus name. GOD BLESS YOU.",
  "The Almighty God will lift you up far above all your reproaches in Jesus name. GOD BLESS YOU.",
  "The Almighty God will take over your difficult issues and grant you permanent solution in Jesus name. HAVE A GREAT WEEK.",
  "The Lord God Almighty shall remove every impediment to your supernatural blessings in Jesus name. GOD BLESS YOU.",
  "The Lord will arise and openly fight those who are secretly opposing your advancement in Jesus name. GOD BLESS YOU.",
  "The promises of God that will give you New Name and Identity shall be fulfilled in your life in Jesus name. GOD BLESS YOU",
  "Your efforts shall be positively fruitful in Jesus name. GOD BLESS YOU",
  "As the Lord lives, You will break limitations and New grounds in Jesus name. GOD BLESS YOU.",
  "May the Lord give you Earth-shaken Testimonies and mind-blowing miracles in Jesus name. GOD BLESS YOU",
  "The Lord will make you laugh again and give you reasons to leap for joy in Jesus name. GOD BLESS YOU.",
  "Life will surely be easy and comfortable for you and your family in Jesus name. GOD BLESS YOU.",
  "Despite the hardship all over, the Lord will supply all your needs according to His riches in glory in Jesus name. HAVE A PROSPEROUS WEEK.",
  "Your Breakthroughs shall come earlier than you expected in Jesus name. GOD BLESS YOU.",
  "The everlasting Arm of the Most High shall lift you high above every flood of your life in Jesus name. GOD BLESS YOU.",
  "Every opportunity you have lost in the past shall be miraculously restored to you with honour in Jesus name. GOD BLESS YOU.",
  "Your appointment with untimely death is cancelled in Jesus name. SHALOM!",
  "At last, your testimony will be ''I never knew that God will answer me this way\" in Jesus name. GOD BLESS YOU.",
  "Your dry season and desert experience is over in Jesus name. GOD BLESS YOU.",
  "Every disappointment you have suffered in life shall be turned to supernatural blessings for you in Jesus name. GOD BLESS YOU",
  "Your mockers will loose their voice and pride over you and your family.in Jesus name. SHALOM!",
  "Your Rivers of Joy and Happiness will never run dry in Jesus name. GOD BLESS YOU.",
  "The Lord will move you from glory to glory. Shame and disgrace shall be far from you in Jesus name. HAVE A GREAT WEEK.",
  "Anyone who is looking for your downfall shall be disappointed with your success in Jesus name. GOD BLESS YOU.",
  "Voice of congratulations and rejoicing with new songs of praises to God shall be your portion now and forever in Jesus name. SHALOM!",
  "Your labour without results is over forever in Jesus name. GOD BLESS YOU.",
  "Your good dreams and glorious expectations will surely manifest and translate into great testimonies in Jesus name. HAVE A GREAT WEEK.",
  "The Almighty God will not allow the enemy to rejoice over you and your household in Jesus name. GOD BLESS YOU.",
  "The God of heaven shall keep you from all harms. He will increase your Joy to the fullest in Jesus name. SHALOM!",
  "Every satanic umbrella preventing the heavenly showers of blessings from falling on you is set ablaze in Jesus name. GOD BLESS YOU.",
  "Every seed and root of impossibility in your life and family is uprooted in Jesus name. GOD BLESS YOU",
  "By the power in the BLOOD of Jesus, anything called terminal disease is terminated in your life in Jesus name. PEACE BE UNTO YOU.",
  "Every mountain standing between you and the fulfillment of your God-given dream shall be removed in Jesus name. SHALOM!",
  "May the Lord give you JOY and rest of mind in every aspect of your life in Jesus name. GOD BLESS YOU.",
  "Your blessings in the camp of the enemies are released by fire in Jesus name. GOD BLESS YOU.",
  "Everything that has not been working well in your life before will begin to work well from this moment in Jesus name. GOD BLESS YOU.",
  "May the Lord paralyze the activities of the devil and his cohorts in your life and family in Jesus name.",
  "Every power sent from the pit of hell to waste your destiny shall be buried alive in Jesus name. GOD BLESS YOU.",
  "Where you cannot speak and defend yourself, divine mercy will speak and defend you in Jesus name. GOD BLESS YOU.",
  "The Almighty God will announce your undeniable FAVOUR with unprecedented TESTIMONIES in Jesus name. GOD BLESS YOU",
  "Anything that could not overcome Jesus will not be able to overcome you too in Jesus name. GOD BLESS YOU.",
  "Every single day of your life shall be full of rejoicing and happiness in Jesus name. GOD BLESS YOU.",
  "By the grace of God, you and your family will begin to experience a new level of comfort, progress and achievements in Jesus name. SHALOM!",
  "Garment of sorrow prepared for you and your family by the devil is set ablaze in Jesus name. GOD BLESS YOU",
  "As the Lord lives, you will prevail over all your challenges in Jesus name. HAVE A GREAT WEEK",
  "I command every evil arrow fired against your health, finance and family to backfire now in Jesus name. GOD BLESS YOU.",
  "Your goods in the warehouse of the devil are released by fire in Jesus name. GOD BLESS YOU.",
  "Every negative word spoken in to your life and destiny is cancelled in Jesus name. GOD BLESS YOU.",
  "Your path to greatness and success shall not be blocked in Jesus name. SHALOM!.",
  "Any man or woman that joins force with the devil to afflict you shall be openly disgraced in Jesus name. GOD BLESS YOU.",
  "Every power sent to crumble your life and your family shall be shattered in Jesus name. GOD BLESS YOU.",
  "Whatever evil the enemy has planned against you and your family will not succeed in Jesus name. GOD BLESS YOU.",
  "That expected miracle already tagged with your name will surely come your way. It will not elude you in Jesus name. GOD BLESS YOU.",
  "The Lord Almighty God will make it impossible for the enemy to rejoice over you in Jesus name. GOD BLESS YOU.",
  "The Lord God will re-package, re-brand and re-introduce you to the world in Jesus name. GOD BLESS YOU",
  "All those out of envy and wickedness waiting for your downfall shall wait in vain forever in Jesus name. GOD BLESS YOU.",
  "May the Lord open the book of remembrance concerning you and your family. May God remember you for good in Jesus name.",
  "Every evil dream that wants to bring affliction and sickness into your life is cancelled in Jesus name. GOD BLESS YOU.",
  "By the power in the name of Jesus, generational curses and poverty will not be passed on to you in Jesus name. GOD BLESS YOU.",
  "Every strongman behind your predicament shall be disgraced in Jesus name. GOD BLESS YOU.",
  "The Lord will empower you to Reign and Rule over every evil power that has been ruling over you before in Jesus name. HAVE A GREAT WEEK.",
  "Your cup of blessings shall begin to overflow. Doors of supernatural blessings shall be opened unto you and your family in Jesus name. GOD BLESS YOU.",
  "You will triumph and prevail over all your challenges and battles in Jesus name. GOD BLESS YOU.",
  "No arrow of waster shall prosper against you and your family in Jesus name. GOD BLESS YOU.",
  "Whatever it will cause heaven for you to sing a new song, the Lord will do it in Jesus name. HAVE A GREAT WEEK.",
  "The Almighty God will step into your situation and silence the enemies that are working against your progress in Jesus name. SHALOM!",
  "Every satanic pronouncement issued to destroy your life and destiny is cancelled in Jesus name. SHALOM!",
  "Every hindrance to your open heaven is removed in Jesus name. May God open your heaven of breakthrough. GOD BLESS YOU.",
  "May the Light of the Lord swallow up every darkness in your life and family in Jesus name. GOD BLESS YOU.",
  "Your source of Joy will not turn to source of sorrow in Jesus name. GOD BLESS YOU.",
  "Every demonic viper that has handcuffed your hands is destroyed by fire in Jesus name. GOD BLESS YOU.",
  "The Angels of God assigned to you shall fulfil God,s mandate concerning your life in Jesus name. GOD BLESS YOU.",
  "May the Lord cast away everything that is not of God from your life and family in Jesus name. GOD BLESS YOU.",
  "Every power diverting your blessings and goodness to a wrong destination is cursed in Jesus name. GOD BLESS YOU.",
  "Every limitation placed on your life by the devil is removed in Jesus name. GOD BLESS YOU.",
  "Every evil word spoken to stagnate your progress is reversed by fire in Jesus name. HAVE A GREAT WEEK.",
  "The Almighty God will make you a Blessing to your generation in Jesus name. GOD BLESS YOU.",
  "In a hard time like this, the Almighty God will make life better for you and your family in Jesus name. HAVE A PROSPEROUS WEEK.",
  "Your glory will not sink in the mighty name of Jesus. GOD BLESS YOU.",
  "The Lord will open every locked door hindering your breakthrough in Jesus name. GOD BLESS YOU.",
  "All the angels assigned to your life shall deliver God's mandate concerning you in Jesus name. GOD BLESS YOU.",
  "Where men say it is over for you, May the Lord take over your case from there and surprise you in Jesus name. GOD BLESS YOU.",
  "May you become all the Lord created you to be in Jesus name. SHALOM!",
  "May all seemingly impossible situations of your life receive divine touch in Jesus name. GOD BLESS YOU.",
  "The Lord will reload and rebrand your life, job and business with wonders in Jesus name. GOD BLESS YOU.",
  "Oppositions against you and your family shall be defeated and disappointed in Jesus name. GOD BLESS YOU.",
  "The voice of the devil in your life and family shall be silenced for ever in Jesus name. SHALOM!",
  "May the Lord single you and your family out for unprecedented favour in Jesus name. GOD BLESS YOU.",
  "May the Lord give you good results in all your Labour in Jesus name. GOD BLESS YOU.",
  "May the Lord compensate you in many folds for any loss you might have suffered in Jesus name. SHALOM!",
  "Every arrow of shame sent against you and your family shall backfire in Jesus name. GOD BLESS YOU.",
  "The grace that opens doors of great opportunities shall be released unto you in Jesus name. GOD BLESS YOU.",
  "May the Lord in His infinite mercy hasten the fulfillment of your heart desires in Jesus name. SHALOM!",
  "The dream of your heart, prayers of your lips and expectations of your heart shall come to reality in Jesus name. GOD BLESS YOU.",
  "May the Lord set you free from every siege and bondage. May your life experience liberation in every area in Jesus name. GOD BLESS YOU.",
  "Every evil power harvesting your good rewards shall die by fire in Jesus name. SHALOM!",
  "No matter how hard things are for you now, very soon you will swim in abundance in Jesus name. GOD BLESS YOU.",
  "Every power delaying your miracles is paralyzed in Jesus name. GOD BLESS YOU.",
  "All the damages done to your life and family by the enemy is repaired in Jesus name. GOD BLESS YOU.",
  "By the grace of God, your enemies will never triumph over you in Jesus name. SHALOM!",
  "The Lord will bless you and protect you and your family from all forms of sicknesses in Jesus name. HAVE A GREAT WEEK.",
  "Failure at the edge of breakthrough will never be your portion again in Jesus name. GOD BLESS YOU.",
  "The storms of life you are going through now will never sink the boat of your life in Jesus name. GOD BLESS YOU.",
  "May the Lord show you the way to go and teach you what to do to move forward in Jesus name. SHALOM!",
  "Your journey will not end in the wilderness of life, you will surely get to your promise land in Jesus name. SHALOM!",
  "Every plan of the evil ones to harm you and your family shall backfire in Jesus name. GOD BLESS YOU.",
  "The Almighty God who is JEHOVAH JIREH--Our provider, shall meet ALL your needs in Jesus name. GOD BLESS YOU.",
  "May the Lord lift you above the storm and challenge you are going through in Jesus name. GOD BLESS YOU.",
  "Opportunities that will change your story for the better shall come your way in Jesus name. SHALOM!",
  "The Lord will put special mark of \"*greatness\" and \"excellence\"* on you and your family in Jesus name. GOD BLESS YOU.",
  "Every covenant that untimely death has made with you is cancelled in Jesus name. GOD BLESS YOU",
  "May the Lord turn your darkness to LIGHT and make your rough paths smooth in Jesus name GOD BLESS YOU.",
  "May the Lord take away your pains and heal all your wounds in Jesus name. GOD BLESS YOU.",
  "May the Lord fulfill all His promises concerning you and your family in Jesus name. God bless you.",
  "The wind that is meant to harm you shall be turned for your advancement in Jesus name. SHALOM!",
  "You shall rise above your challenges by the Grace of God in Jesus name. GOD BLESS YOU.",
  "Bareness in every aspect of your life is rebuked in Jesus name. GOD BLESS YOU.",
  "Any sickness that will make your life miserable will never come your way in Jesus name. GOD BLESS YOU.",
  "Every arrow of affliction sent to destroy your life shall backfire in Jesus name. SHALO!",
  "You will never fail nor fall again in Jesus name. GOD BLESS YOU",
  "Every covenant of poverty with your life is broken in Jesus name. GOD BLESS YOU.",
  "All the plans of the devil to disgrace you and put you to shame shall be nullified in Jesus name. SHALOM!",
  "All the doors of opportunities and privileges hitherto shut against your life shall be opened by the power of Holy Ghost in Jesus name. HAVE A PROSPEROUS WEEK.",
  "Your worries shall turn to wonders and celebrations in Jesus name. GOD BLESS YOU.",
  "The great earthquake that is going to break open the cloud of your latter rain shall happen in Jesus name. GOD BLESS YOU.",
  "That report that is disturbing you shall not come to fulfilment in Jesus name. GOD BLESS YOU.",
  "May the Lord be a shelter and shade for you from the heat of life and a hiding place for you from the storms of life in Jesus name. SHALOM!",
  "The Almighty God shall break protocols and systems to take you to your next level in Jesus name. HAVE A GREAT WEEK.",
  "Your life and everything about you shall proclaim the glory and power of God in Jesus name. GOD BLESS YOU.",
  "The miraculous hands of God shall pull you out of that challenge in Jesus name. GOD BLESS YOU.",
  "The Voice of the Lord shall stand out for you no matter the noise around your life in Jesus name. GOD BLESS YOU.",
  "May the Lord make you Comfortable in every area of your life in Jesus name. GOD BLESS YOU.",
  "Every appointment your destiny has made with untimely death is cancelled in Jesus name. GOD BLESS YOU.",
  "May the Lord turn your bitter experiences to sweet experiences before the year runs out in Jesus name. GOD BLESS YOU",
  "As the year runs to an end, the Lord will put an end to struggling and hardship in your life in Jesus name. GOD BLESS YOU",
  "Every manipulation aimed at bringing you shame shall be overturned in Jesus name. GOD BLESS YOU.",
  "As the year runs to an end, May you experience total Restoration in every aspect of your life in Jesus name. SHALOM!",
  "Every RED SEA on your way to the PROMISED LAND will see the glory of God and disappear before you in Jesus name. GOD BLESS YOU.",
  "May His Birth bring you Great Joy. May His Birth bring Light to your life. May His Birth bring Hope to your hopeless situations. May His Birth bring divine Peace to your life. May His Birth Settle your Case. May His Birth bring Answer to the questions of your life. HAPPY CHRISTMAS.",
  "Every GIFT and BLESSING the Lord has prepared for shall be delivered unto you before the year runs out in Jesus name. SEASON GREETINGS.",
  "May the God of All Peace smile on you and equip you with every good thing for living in Jesus name. SEASON GREETINGS.",
  "May the Almighty God carry you on His wings and move you above all limitations and barriers in Jesus name. GOD BLESS YOU.",
  "May the power of God melt away all the burdens that are threatening your peace in Jesus name. GOD BLESS YOU.",
  "Every garment of shame prepared for you and your family by the enemy shall be consumed by fire in Jesus name. GOD BLESS YOU.",
  "No more dry season in your life, family and business in Jesus name. GOD BLESS YOU.",
  "The Lord will put an end to your secret tears and give you public celebration in Jesus name. GOD BLESS YOU.",
  "May the Lord give you divine speed to achieve your goals in Jesus name. GOD BLESS YOU.",
  "May the Lord crown all your efforts in life with outstanding success in Jesus name. GOD BLESS YOU.",
  "The Lord will divinely Restore and Repair all that you have lost in Jesus name. SHALOM!",
  "Your efforts in life will not end up in tragedy in Jesus name. GOD BLESS YOU",
  "Every wall of Jericho standing between you and your inheritance shall fall down and sink into the ground in Jesus name. GOD BLESS YOU.",
  "The Almighty God will decorate your life with new things in Jesus name. SHALOM!",
  "May the Lord decorate your life with honour and prosperity in Jesus name. GOD BLESS YOU.",
  "Receive the grace to stand and prevail against all odds in Jesus name. GOD BLESS YOU",
  "Whatever that is troubling your life shall be troubled by God in Jesus name. GOD BLESS YOU",
  "No enchantment and divination from the pit of hell shall succeed against you and your family in Jesus name. GOD BLESS YOU",
  "All the powers waiting for your downfall shall wait in vain for ever in Jesus name. GOD BLESS YOU.",
  "Every incident that will cause you sorrow, weeping, crying, mourning and gnashing of teeth is cancelled in your life in Jesus name. GOD BLESS YOU",
  "The Holy Spirit will deliver unto you Miracles that appear impossible and Favour that brings confusion to the enemy in Jesus name. GOD BLESS YOU.",
  "The Lord will visit your life and home with good tidings and put new songs in your mouth in Jesus name. GOD BLESS YOU.",
  "Every chain that has been holding you back is broken in the name of Jesus. GOD BLESS YOU.",
  "May the Lord convert your secret tears to public celebrations and jubilations in Jesus name. GOD BLESS YOU",
  "May the blessings of the Lord overflow in every area of your life in Jesus name. GOD BLESS YOU.",
  "May the Mercy of the Lord reign supreme over every judgement of man and the devil in your life in Jesus name. SHALOM!",
  "May the Lord use everything in creation to bring you GOOD NEWS in Jesus name. GOD BLESS YOU.",
  "Your life and everything about you shall advertise the glory of the Lord in Jesus name. GOD BLESS YOU",
  "The kind of Favour that will make your enemies to be at peace with you shall come upon you in Jesus name. GOD BLESS YOU.",
  "The Favour that will set aside your sins, mistakes and failures for a New beginning shall be poured upon you in Jesus name. SHALOM!",
  "The Favour that will make you a channel of blessings to others shall come upon you in Jesus name. GOD BLESS YOU.",
  "Every evil plan against you and your family shall be frustrated and disappointed in Jesus name. GOD BLESS YOU.",
  "The Favour that will Restore your lost opportunities shall fall on you in Jesus name amen. GOD BLESS YOU.",
  "May the God of Vengeance show Himself strong on your behalf in Jesus name. SHALOM!",
  "You will never know defeat anymore in your life, family and job in Jesus name. HAVE A PROSPEROUS WEEK.",
  "May the Lord Remember your Kingdom Sacrifices and put a Smile on your face in Jesus name. GOD BLESS YOU.",
  "The Lord shall send help to you speedily in Jesus name. GOD BLESS YOU.",
  "May the Lord take you to the next level of glory you have been waiting for in Jesus name. GOD BLESS YOU.",
  "Every power sent to waste and delay your time shall be buried alive in Jesus name. SHALOM!",
  "May God fight for you and save you from all life threatening situations in Jesus name. GOD BLESS YOU.",
  "Everything about you shall be fine! One day you shall be thankful to God that you never gave up. GOD BLESS YOU.",
  "Every power waiting to harm you and your family shall be roasted by fire in Jesus name. SHALOM!",
  "Your life shall prove to the world that God is Good and Real in Jesus name. HAVE A PROSPEROUS WEEK.",
  "May the Light of Christ Shine more brighter on you and remove every darkness from your life in Jesus name. GOD BLESS YOU.",
  "May you receive Divine Attention to all your issues in Jesus name. SHALOM!",
  "May the Lord keep you Divinely Connected and create avenues for miracles to reach you in Jesus name. SHALOM!",
  "The Lord will cloth you with the garment of Favour, Mercy and Glory in Jesus name. GOD BLESS YOU.",
  "The Lord will take away shame and reproach from your life in Jesus name. GOD BLESS YOU.",
  "The Almighty God will continue to be your portion and you will never be put to shame in Jesus name. GOD BLESS YOU",
  "The Lord will give you Reasons for Celebration in Jesus name. SHALOM!",
  "The on-going work of God in your life shall be completely accomplished in Jesus name. HAVE A GREAT WEEK. .",
  "Where human help and ability stop in your life, the mighty hand of God shall carry you and give you solution in Jesus name. GOD BLESS YOU.",
  "The Lord will answer you and deliver you from all your fears in Jesus name. GOD BLESS YOU.",
  "The Lord will turn your darkness to light and make your light to keep on shinning in Jesus name. GOD BLESS YOU",
  "May the Lord open New doors of opportunities for you in Jesus name. HAVE A GREAT WEEK.",
  "The Lord will lift you up and help you to achieve your set goals in Jesus name. GOD BLESS YOU.",
  "The Almighty God will help you to succeed in every area of your life in Jesus name. GOD BLESS YOU",
  "Your life will continue to shine brightly in Jesus name. GOD BLESS YOU",
  "The Lord will build a wall of fire around you and everything that belongs to you in Jesus name. SHALOM!",
  "The Lord will not allow the pronouncement of the wicked to be fulfilled in your life in Jesus name. GOD BLESS YOU.",
  "May the Lord fast track your progress and give you pleasant surprises in Jesus name. GOD BLESS YOU.",
  "May the Lord give you speed and acceleration where others are struggling to find way in Jesus name. GOD BLESS YOU",
  "The Lord will put an end to that \"OLD SONG' in your life and give you \"NEW SONG\" of praise and Thanksgiving to sing in Jesus name. GOD BLESS YOU.",
  "May the Lord take you to the new level of abundance and more than enough in Jesus name. SHALOM!",
  "May the Lord establish you and make you walk in the high places by His mighty power in Jesus name. GOD BLESS YOU",
  "May the Lord accelerate your achievements in life by His Mercy in Jesus name. GOD BLESS YOU",
  "Every dream that translates to death, sickness, poverty and failure will never come to fulfilment in your life in Jesus name. GOD BLESS YOU",
  "Your labour will not be in vain. The Lord will crown your efforts with favour and success in Jesus name. SHALOM!",
  "The Lord will bring about the positive and meaningful turnaround that your life needs in Jesus name. GOD BLESS YOU.",
  "May the Lord amend and repair those damaged portions of your life in Jesus name. GOD BLESS YOU.",
  "May the Lord shield you from harm and lead you into prosperity in Jesus name. GOD BLESS YOU.",
  "Events that will increase your Joy and Happiness shall manifest in your life inJesus name SHALOM!",
  "The Almighty God will renew his covenant of long life and prosperity in your life in Jesus name. HAVE A PROSPEROUS WEEK",
  "Your life will be a living testimony of the goodness and faithfulness of God in Jesus name. GOD BLESS YOU.",
  "God's kindness and faithfulness will never depart from you and your family in Jesus name. GOD BLESS YOU.",
  "The Lord will surround you with His Favour, Joy and Peace in Jesus name. GOD BLESS YOU.",
  "May the Almighty God supernaturally connect you to your destiny helpers in Jesus name. SHALOM!",
  "The Lord Almighty God will unseat every power that sits on your glory in Jesus name. GOD BLESS YOU.",
  "Heaven will bless you with new Ideas that will open New doors of opportunities for you in Jesus name. GOD BLESS YOU",
  "Every mountain standing between you and the fulfillment of your God-given dream shall become plain in Jesus name. GOD BLESS YOU.",
  "Favour that will set aside your mistakes and failures shall locate you in Jesus name. SHALOM!",
  "The Lord will minister divine solutions to your challenges in Jesus name. GOD BLESS YOU.",
  "May the Lord hide you and your family in His secret place from all evils in Jesus name. GOD BLESS YOU.",
  "Your Rising will no longer be hindered by any force in Jesus name amen. GOD BLESS YOU.",
  "Every evil mark and negative pronouncement placed on you and your family are cancelled in Jesus name. SHALOM!",
  "Happy Father's Day to All our wonderful, responsible and committed fathers. May we never labour in vain. May we live long enough to enjoy the labour of our hands. May we together with our wives enjoy our labour over our children in Jesus name Remain Blessed.",
  "The Lord will protect you and your family from all forms of demonic agendas in Jesus name. GOD BLESS YOU",
  "The Lord will make you a candidate of Divine Favour in Jesus name. GOD BLESS YOU",
  "The Lord will heal your wounds and wipe away your tears in Jesus name. GOD BLESS YOU.",
  "Every Red Sea before you shall be parted by the mighty hands of God in Jesus name. GOD BLESS YOU",
  "May the Lord hide you and your family in His Secret place for shelter and security in Jesus name. GOD BLESS YOU.",
  "As the first half of the year is gradually winding down, May God crown your efforts with outstanding results in Jesus name. GOD BLESS YOU.",
  "May the Lord remove every obstacle from your way to breakthrough and fulfillment in Jesus name. SHALOM.",
  "No good thing on this planet earth shall elude you in Jesus name. HAVE A GREAT WEEK.",
  "Rain of sorrow and affliction will not fall on you and your family in Jesus name. GOD BLESS YOU.",
  "All your good efforts shall produce wonderful testimonies in Jesus name. GOD BLESS YOU.",
  "Doors of progress and breakthrough shall never be shut against you anymore in Jesus name. GOD BLESS YOU.",
  "Every chapter closed by men against you shall be reopened by God with favour in Jesus name. SHALOM.",
  "The Almighty God will step into your situation and restore your lost fortunes in Jesus name. GOD BLESS YOU",
  "The Favour of the Lord will locate you and hasten your journey into breakthrough in Jesus name. GOD BLESS YOU.",
  "The might to triumph and the grace to have dominion shall be endowed you in Jesus name. GOD BLESS YOU.",
  "The Lord shall intervene in your situation. Those waiting for your downfall shall forever wait in vain in Jesus name. SHALOM!",
  "God will give you a New Beginning and make your life better than you were before in Jesus name. GOD BLESS YOU.",
  "You will never fall into the pit that the enemy had dug for you in Jesus name. GOD BLESS YOU.",
  "May the Almighty God satisfy you with long life and every good thing you need to enjoy your life on this earth in Jesus name. SHALOM!",
  "Your struggles in life will never be in vain. God will crown your efforts with outstanding results in Jesus name. SHALOM!",
  "The Lord will give you a sudden miracle that will put an end to your struggles and pains in Jesus name. GOD BLESS YOU.",
  "The Lord shall bring to an end all forces assigned by the devil to waste your efforts in Jesus name. GOD BLESS YOU.",
  "The Lord will turn your silent prayers to public testimonies in Jesus name. GOD BLESS YOU",
  "May the Lord protect you from every projected storm and sickness from the Camp of enemy in Jesus name. GOD BLESS YOU",
  "The Lord will arise and defend you in all your challenges in Jesus name. GOD BLESS YOU.",
  "Every aspect of your life that is barren shall become fruitful in Jesus name. SHALOM!",
  "You and your family shall be established in the Mercy of God in Jesus name. GOD BLESS YOU.",
  "The WIND of mercy and favour shall blow mightily upon you and your family in Jesus name. GOD BLESS YOU",
  "Every challenge affecting your life shall be transformed into testimony in Jesus name. GOD BLESS YOU.",
  "The God of Restoration shall visit you and bring restoration to every aspect of your life in Jesus name. SHALOM!",
  "May the Almighty God empower you to outrun your past setbacks and recover all that you have lost in Jesus name. GOD BLESS YOU.",
  "A new chapter of favour and wonders is opened for you and your family in Jesus name. GOD BLESS YOU",
  "The Almighty God will override systems to bring His purpose to pass in your life in Jesus name. SHALOM!",
  "Every power that wants to hinder your progress shall be buried alive in Jesus name. GOD BLESS YOU.",
  "Your destiny helpers shall locate you and help you before it is too late in Jesus name. GOD BLESS YOU",
  "Your shall rise above all your limitations and barriers in Jesus name. SHALOM!",
  "May the Lord make you a blessing to your generation. May you be fruitful in every area of life in Jesus name. GOD BLESS YOU",
  "The Lord will make you a solution provider to your generation in Jesus name. GOD BLESS YOU.",
  "In the same place where you have been insulted and rejected, May God turn you to a celebrity in Jesus name. SHALOM!",
  "May the God of Hope renew your Hope and may your expectations never be cut short in Jesus name. GOD BLESS YOU",
  "May the Almighty God shield you and your family from every demonic arrow hunting after your life in Jesus name. GOD BLESS YOU.",
  "The Lord will fight for you and your adversaries shall be shamefully silenced in Jesus name. GOD BLESS YOU.",
  "May the Lord reward all your efforts with outstanding fruitfulness in Jesus name. GOD BLESS YOU",
  "May the Lord lift you up and cause you to rise above every challenge in Jesus name. GOD BLESS YOU.",
  "May the counsel of the wicked be rendered ineffective in your life and family in Jesus name. SHALOM!",
  "Any junction where disgrace is waiting for you shall be scattered by fire in Jesus name. GOD BLESS YOU.",
  "Every obstacle before you shall bow to the greatness of God in your life in Jesus name. GOD BLESS YOU.",
  "Every valley before you shall be raised up and every mountain shall be made low in Jesus name. SHALOM!",
  "May the voice of the Lord sounds more louder than the voice of any opposition in your life in Jesus name. GOD BLESS YOU.",
  "The invisible hand of God shall lift you up and pull you out of every oppression in Jesus name. GOD BLESS YOU.",
  "Where it seems impossible, the Lord will make way for you in Jesus name. GOD BLESS YOU",
  "Your past mistakes shall be converted to miracles for you in Jesus name. GOD BLESS YOU.",
  "The portals of great opportunities shall open wide for you and your family in Jesus name. GOD BLESS YOU",
  "The Almighty God will make you a channel of blessings to others in Jesus name. GOD BLESS YOU",
  "Everything that you are going through shall eventually be for your good in Jesus name. GOD BLESS YOU.",
  "Your moment of divine visitation and breakthrough will not pass you by in Jesus name. GOD BLESS YOU",
  "As the Lord lives, you are coming out of your challenges victoriously in Jesus name. GOD BLESS YOU",
  "The Lord will intervene in your life where you are helpless and confused in Jesus name. SHALOM!",
  "The Lord will divinely repair and restore all that you have lost in the past in Jesus name. GOD BLESS YOU.",
  "You are the next in line to testify, and great celebration shall be your portion in Jesus name. SHALOM!",
  "May God make a way of escape from every trouble for you and usher you into a season of unprecedented victory in Jesus name. GOD BLESS YOU.",
  "Your nights of weeping shall give way for Joyous morning in Jesus name. GOD BLESS YOU.",
  "May the Lord save you from the hands of the wicked and redeem you from the grip of the cruel in Jesus name. GOD BLESS YOU.",
  "May your life overflow with the goodness of the Lord in Jesus name. GOD BLESS YOU.",
  "Your mouth shall overflow with testimonies of God's goodness in Jesus name. GOD BLESS YOU",
  "May the Lord answer your secret prayers with public celebration in Jesus name. GOD BLESS YOU.",
  "May the Lord renew His covenant with you just as He did with Abraham, Isaac and Jacob in Jesus name. GOD BLESS YOU.",
  "The unfruitful works of darkness will not prevail over you and your family in Jesus name. SHALOM.",
  "The Lord will shield you and your family from every evil arrow in Jesus name. GOD BLESS YOU.",
  "The Lord will fight for you and you will see the manifestation of His power in a new dimension in Jesus name. GOD BLESS YOU.",
  "The Lord who is sufficient in All things will supply your needs in a miraculous way in Jesus name. GOD BLESS YOU.",
  "May timely helpers arise to support you in all your endeavours in Jesus name. SHALOM!",
  "Your good dreams shall become realities while you are still alive in Jesus name. GOD BLESS YOU.",
  "The Lord who is self-sufficient shall activate His riches in your life and make you a blessing to others in Jesus name. GOD BLESS YOU.",
  "Jesus was born to be THE SOLUTION to human problems. May the Lord graciously give you ONE GIFT that will bring fulfilment to your destiny and give true meaning to your life this season in Jesus name. HAPPY CHRISTMAS.",
  "May the mighty hand of God delete every ugly event from your life in Jesus name. GOD BLESS YOU.",
  "May the Lord make your life a testament of His goodness and faithfulness in Jesus name. GOD BLESS YOU.",
  "Your past failures shall be turned into a remarkable successes in your life in Jesus name. GOD BLESS YOU.",
  "Every demonic force designed to hinder your progress shall be buried alive in Jesus name. GOD BLESS YOU.",
  "Every voice of doubt and negativity speaking in your heart is silenced in Jesus name. SHALOM!",
  "May every effort you have made begin to yield abundant fruits in Jesus name. GOD BLESS YOU.",
  "May the Lord wipe away every tear from your eyes and fill your mouth with laughter in Jesus name. GOD BLESS YOU.",
  "Every gatekeeper of darkness that wants to bar you from entering into your promised inheritance shall be struck dead in Jesus name. GOD BLESS YOU",
  "The Holy Spirit shall liberate you and your household from every yoke of bondage in Jesus name. GOD BLESS YOU",
  "May the Lord give you Divine Ideas to overtake those that have gone ahead of you in Jesus name. GOD BLESS YOU.",
  "Every yoke of oppression in your life and family is broken in Jesus name. GOD BLESS YOU.",
  "May the Lord be deliberate and intentional to favour you against all odds in Jesus name. GOD BLESS YOU.",
  "The Almighty God will put an end to scarcity of good things in your life in Jesus name. GOD BLESS YOU.",
  "Every effort you put forth shall attract divine attention and yield fruitful results in Jesus name. GOD BLESS YOU",
  "Every satanic force trying to control your life, family and career shall be rendered powerless in Jesus name. GOD BLESS YOU.",
  "Those who await your downfall shall witness your ascent to the glory of God in Jesus name. REMAIN BLESSED!",
  "You will break forth, you will expand and gain access to new opportunities in Jesus name. GOD BLESS YOU.",
  "The Almighty God will remember you for good and shower His blessings on you in Jesus name. GOD BLESS YOU.",
  "The voice of rejoicing and praises shall be forever heard in your dwelling in Jesus name. SHALOM!",
  "Every challenge before you shall bow to divine authority and you shall triumph victoriously in Jesus name. GOD BLESS YOU",
  "Henceforth, no obstacle or challenge will be strong enough to hinder your progress in Jesus name. GOD BLESS YOU.",
  "No force from the pit of hell shall be strong enough to take your Joy away from you in Jesus name. GOD BLESS YOU.",
  "The Lord shall subdue every mountain and wall against your progress in Jesus name. SHALOM!",
  "The Light of Christ shall illuminate every dark area of your life and expose the work of darkness in Jesus name. GOD BLESS YOU.",
  "Your acts of kindness and generosity shall not go unrewarded in Jesus name. REMAIN BLESSED.",
  "Those waiting for your downfall shall forever wait in vain and disappointment in Jesus name. GOD BLESS YOU.",
  "The Lord will frustrate the plans of the wicked over you and your family in Jesus name. GOD BLESS YOU.",
  "Every wicked plan to harm you and your family shall be exposed and destroyed in Jesus name. GOD BLESS YOU.",
  "May your heaven of divine favour remains perpetually open in Jesus name. GOD BLESS YOU.",
  "May the Lord smile upon you and your family and bring to remembrance His promises concerning you in Jesus name. GOD BLESS YOU.",
  "The Lord will turn your desert to a virgin and productive land in Jesus name. GOD BLESS YOU",
  "The mother of Pastor D.O.B.Osundeyi has gone to be with the Lord! Let us commiserate with the family please!",
  "Like a tree planted by the streams of water, May you flourish in every area of life in Jesus name. GOD BLESS YOU",
  "Every demonic chain holding you down is broken in Jesus name. GOD BLESS YOU.",
  "May the Lord make your prayers this season fruitful and effective in Jesus name. SHALOM!",
  "Your small effort shall yield great and unprecedented results in Jesus name. GOD BLESS YOU.",
  "May the Lord visit your home with good tidings and put songs of celebration in your mouth in Jesus name. GOD BLESS YOU",
  "Your nights of sorrow shall give way to a glorious morning in Jesus name. GOD BLESS YOU.",
  "Your season of disappointment, regrets, frustration, pains, sorrow and shame is over in Jesus name. GOD BLESS YOU.",
  "Your new chapter of life full of glory and testimonies begins now in Jesus name. SHALOM!",
  "No impediment shall be strong enough to hinder your movement into fulfilment and glory in Jesus name. HAVE A PROSPEROUS WEEK.",
  "*PEACE BE UNTO YOU IN JESUS NAME* Beloved in Christ, I am indeed overwhelmed with your birthday wishes. I sincerely appreciate your love and your gifts. May the Lord continue to keep us together in His love. May the Lord give you reasons for celebration in Jesus. God bless you all.",
  "May the Lord carry you on eagle's wings and may you soar above every limitation and challenge in Jesus name. GOD BLESS YOU.",
  "Your progress and answer to prayers shall be evident and visible to all in Jesus name. GOD BLESS YOU.",
  "The Almighty God will gladden your heart from every side and your adversaries shall be utterly disgraced in Jesus name. GOD BLESS YOU.",
  "The power of Resurrection will turn things around for good for you and your family in Jesus name. HAPPY EASTER.",
  "May the Lord's compassion renew your life and May His providence bring turnaround into every area of your life in Jesus name. GOD BLESS YOU.",
  "Every promise of the word of God concerning your life and your family shall manifest without delay in Jesus name. GOD BLESS YOU.",
  "Every stone of hindrance set against your rising shall be forcefully rolled away in Jesus name. GOD BLESS YOU.",
  "The Almighty God will restore to you your lost opportunities in Jesus name. GOD BLESS YOU",
  "You will not mourn over any of your family members in Jesus name. GOD BLESS YOU.",
  "The Almighty God will not allow destiny destroyers to have access to your destiny in Jesus name GOD BLESS YOU.",
  "The better and bigger thing that the Lord is preparing for you will surely manifest in Jesus name. HAVE A GREAT WEEK.",
  "The glory that the Lord has deposited in you shall manifest against all odds in Jesus name. SHALOM!",
  "May the Holy Spirit break every limitation and barrier to your growth and enlargement in Jesus name. SHALOM!",
  "Every appointment your destiny has made with untimely death unknowingly is cancelled in Jesus name. GOD BLESS YOU.",
  "May this day speak PEACE into your life, FAVOUR into your home and INCREASE into your your work in Jesus name. GOD BLESS YOU.",
  "Your seat of honour shall be established in Jesus name. And you shall increase in favour with God and man in Jesus name. HAVE A GREAT WEEK.",
  "The Lord will turn your trials to testimonies and your mourning to dancing in Jesus name. GOD BLESS YOU",
  "May the Lord shield you and your family members from all evils in Jesus name. GOD BLESS YOU.",
  "Whatever is the nature of the storm you are going through, let there be PEACE now in Jesus name. SHALOM!",
  "Every yoke of oppression and satanic burden upon your life is broken in Jesus name. HAVE A PROSPEROUS WEEK",
  "Your ocean of gladness shall know no drought in Jesus name. GOD BLESS YOU.",
  "The lamp of your glory shall continue to burn with increasing splendor day by day without dimming in Jesus name. GOD BLESS YOU",
  "You shall prevail over every adversary and affliction in Jesus name.. GOD BLESS YOU.",
  "Every spiritual craftsman fashioning mischief against you and your family shall be broken by the Almighty God in Jesus name. SHALOM!",
  "Every good purpose set before you shall be established and every righteous mission before shall be accomplished in Jesus name. GOD BLESS YOU.",
  "The Lord will grant you divine acceleration that no force on earth will be able to hinder in Jesus name. GOD BLESS YOU",
  "The seat of honour prepared for you by God shall not be given to another person in Jesus name. GOD BLESS YOU.",
  "By His Grace, you shall rise above all your limitations in Jesus name. GOD BLESS YOU.",
  "The Lord will make the work of your hands to prosper in all that you do in Jesus name. GOD BLESS YOU.",
  "Every demonic chain that has held your life down is broken by fire in Jesus name. GOD BLESS YOU.",
  "May the Lord give you REST over every challenge facing your life in Jesus name. HAVE A GREAT WEEK.",
  "May you begin to walk in the new dimension of Divine Favour from now on in Jesus name. GOD BLESS YOU",
  "Where your heart has waited for good news, sorrow and heaviness shall find no place in Jesus name. GOD BLESS YOU.",
  "I decree by the power of the Holy Ghost every chain of bondage and cycle of setback in your life to be consumed by fire in Jesus name. GOD BLESS YOU.",
  "Happy *FATHER'S DAY* to all our wonderful day responsible fathers. Your commitment and dedication over your family is highly appreciated. May your labour never be in vain. May you live long in good health to enjoy what you have laboured for in Jesus name.. Remain Blessed.",
  "Every blessing stolen from you shall be restored in multiple folds in Jesus name. HAVE A GREAT WEEK.",
  "May God Arise and change your hardship to history in Jesus name. GOD BLESS YOU.",
  "Every power assigned to use your life as a dumping ground shall be buried alive in Jesus name. GOD BLESS YOU.",
  "The Lord will do a new thing in your family, marriage, work and business in Jesus name. GOD BLESS YOU",
  "May the Lord make you laugh over issues that have once made you shed tears in Jesus name. GOD BLESS YOU.",
  "Any power assigned to use your blood for promotion shall be buried alive in Jesus name. GOD BLESS YOU.",
  "Every voice that is declaring that you will not live long shall be silenced in Jesus name. HAVE A GREAT WEEK.",
  "Powers assigned to turn your source of joy to sorrow shall be wasted in Jesus name. GOD BLESS YOU.",
  "The Almighty God will turn your greatest challenges to amazing testimonies in this second half of the year in Jesus name. GOD BLESS YOU",
  "Every power working hard for your demotion shall be consumed by the wrath of God in Jesus name. GOD BLESS YOU",
];
