import { Nav } from "@/components/navigation/Nav";
import { FooterExperience } from "@/components/sections/FooterExperience";
import { Reveal } from "@/components/ui/Reveal";
import Link from "next/link";
import { setRequestLocale } from "next-intl/server";
import type { Metadata } from "next";
import { SITE_URL } from "@/lib/site";
import { routing } from "@/i18n/routing";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const languages = Object.fromEntries(routing.locales.map((l) => [l, `${SITE_URL}/${l}/statement-of-faith`]));
  return {
    title: "Statement of Faith — Christ Apostolic Church North America (CACNA)",
    description:
      "What CACNA believes — the Word of God, the Trinity, Jesus Christ, the Holy Spirit, regeneration, the Church, Christian conduct, the ordinances, religious liberty, church cooperation, and the last things.",
    alternates: { canonical: `${SITE_URL}/${locale}/statement-of-faith`, languages },
  };
}

const articles = [
  {
    title: "The Word of God",
    text: "We believe that the Bible is the Word of God, fully inspired and without error in the original manuscripts, written under the inspiration of the Holy Spirit, and that supreme authority in all matter of faith and conduct.",
  },
  {
    title: "The Trinity",
    text: "We believe that there is one living and true God, eternally existing in three persons, that these are equal in every divine perfection, and that they execute distinct but harmonious offices in the work of creation, providence and redemption.",
  },
  {
    title: "God the Father",
    text: "We believe in God, the Father, an infinite personal holiness, wisdom power, and love. We believe that He concerns Himself mercifully in the affairs of men, that He hears and answers prayer, and that He saves from sin and death all who come to Him through Jesus Christ.",
  },
  {
    title: "Jesus Christ",
    text: "We believe in Jesus Christ, God's only begotten Son, conceived by the Holy Spirit. We believe in His virgin birth, sinless life, miracles and teachings. We believe in His substitutionary atoning death, bodily resurrection, ascension into heaven, perpetual intercession for His people and personal, visible return to earth.",
  },
  {
    title: "The Holy Spirit",
    text: "We believe in the Holy Spirit who came forth from the Son to convict the world of sin righteousness, and judgment, and to regenerate, sanctify, and empower all who believe in Jesus Christ. We believe that the Holy Spirit indwells every believer in Christ, and that He is an abiding helper, teacher and guide.",
  },
  {
    title: "Regeneration",
    text: "We believe that all men are sinners by nature and are, therefore, under condemnation. We believe that those who repent of their sins and trust in Jesus Christ are regenerated by the Holy Spirit.",
  },
  {
    title: "The Church",
    text: "We believe in the universal church, a living spiritual body of which Christ is the head and all regenerated persons are members. We believe in the local church, consisting of a company of believers in Jesus Christ, baptized on a credible profession of faith and associated for worship, work and fellowship. We believe that God has laid upon the members of the local church the primary task of giving the gospel of Jesus Christ to a lost world.",
  },
  {
    title: "Christian Conduct",
    text: "We believe that a Christian should live for the glory of God and the well-being of his fellow men, that his conduct should be blameless before the world, that he should be a faithful steward of his possessions, and that he should seek to realize for himself and others the full stature of maturity in Christ.",
  },
  {
    title: "The Ordinances",
    text: "We believe that the Lord Jesus Christ has committed two ordinances to the local church: baptism and the Lord's Supper. We believe that Christian baptism is the immersion of a believer in water in the name of the triune God. We believe that the Lord's Supper was instituted by Christ for the commemoration of His death. We believe that these two ordinances should be observed and administered until the return of the Lord Jesus Christ.",
  },
  {
    title: "Religious Liberty",
    text: "We believe that every human being has direct relation with God. He is responsible to God alone in all matter of faith, that each church is independent and must be free from interference by any ecclesiastical or political authority. Therefore, Church and State must be kept separate as having different functions, each fulfilling its duties free from dictation or patronage of the other.",
  },
  {
    title: "Church Cooperation",
    text: "We believe that local churches can best promote the cause of Jesus Christ by cooperating with one another in a denominational organization. Such an organization, whether a regional or district conference, exists and functions by the will of the churches. Cooperation in a conference is voluntary and may be terminated at any time. Churches may likewise cooperate with inter-denominational fellowships on a voluntary, independent basis.",
  },
  {
    title: "The Last Things",
    text: "We believe in the personal and visible return of Christ to earth and the establishment of His Kingdom. We believe in the resurrection of the body, the final judgment, the eternal felicity of the righteous, and the endless suffering of the wicked.",
  },
];

export default async function StatementOfFaithPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);

  return (
    <main id="main-content">
      <Nav />

      {/* Hero */}
      <section style={{ background: "var(--cream)", padding: "140px clamp(20px,5vw,64px) 70px", position: "relative", overflow: "hidden" }}>
        <div style={{ position: "absolute", top: -60, right: -60, width: 360, height: 360, borderRadius: "50%", background: "radial-gradient(circle,var(--blue),var(--red) 70%)", opacity: 0.1, filter: "blur(6px)", pointerEvents: "none" }} />
        <div style={{ maxWidth: 780, margin: "0 auto", textAlign: "center", position: "relative", zIndex: 2 }}>
          <Reveal>
            <span style={{ fontSize: 12, fontWeight: 700, letterSpacing: "2.5px", textTransform: "uppercase", color: "var(--red)" }}>What We Believe</span>
          </Reveal>
          <Reveal delay={80}>
            <h1 style={{ fontFamily: "var(--font-display)", fontWeight: 800, fontSize: "clamp(42px,6vw,78px)", letterSpacing: "-0.03em", color: "var(--ink)", margin: "16px 0", lineHeight: 0.96, textWrap: "balance" }}>
              Statement of Faith.
            </h1>
          </Reveal>
          <Reveal delay={160}>
            <p style={{ fontSize: "clamp(16px,1.8vw,19px)", color: "var(--ink-soft)", lineHeight: 1.65, maxWidth: 560, margin: "0 auto" }}>
              Twelve articles that describe what CACNA believes, in plain terms — alongside the Thirteen Tenets of Faith held by the wider Christ Apostolic Church.
            </p>
          </Reveal>
          <Reveal delay={220}>
            <Link href="/about#tenets" style={{ display: "inline-flex", alignItems: "center", gap: 8, marginTop: 24, color: "var(--red)", fontWeight: 700, fontSize: 15, textDecoration: "none" }}>
              See the Thirteen Tenets of Faith →
            </Link>
          </Reveal>
        </div>
      </section>

      {/* Articles */}
      <section style={{ background: "var(--paper)", padding: "clamp(40px,5vw,72px) clamp(20px,5vw,64px) clamp(72px,9vw,110px)" }}>
        <div style={{ maxWidth: 780, margin: "0 auto", display: "flex", flexDirection: "column", gap: 8 }}>
          {articles.map((a, i) => (
            <Reveal key={a.title} delay={Math.min(i * 40, 280)}>
              <div style={{ padding: "26px 0", borderBottom: i < articles.length - 1 ? "1px solid var(--line)" : "none" }}>
                <div style={{ display: "flex", alignItems: "baseline", gap: 14, marginBottom: 10 }}>
                  <span style={{ fontFamily: "var(--font-display)", fontWeight: 800, fontSize: 13, color: "var(--red)", letterSpacing: "1.5px", flexShrink: 0 }}>
                    {String(i + 1).padStart(2, "0")}
                  </span>
                  <h2 style={{ fontFamily: "var(--font-display)", fontWeight: 800, fontSize: 21, letterSpacing: "-.3px", color: "var(--ink)", margin: 0, lineHeight: 1.2 }}>
                    {a.title}
                  </h2>
                </div>
                <p style={{ fontSize: 16, color: "var(--ink-soft)", lineHeight: 1.75, margin: "0 0 0 34px" }}>{a.text}</p>
              </div>
            </Reveal>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section style={{ background: "var(--ink)", padding: "80px clamp(20px,5vw,64px)", textAlign: "center" }}>
        <Reveal>
          <h2 style={{ fontFamily: "var(--font-display)", fontWeight: 800, fontSize: "clamp(32px,4.5vw,52px)", letterSpacing: "-1.2px", color: "var(--cream)", margin: "0 0 16px", lineHeight: 0.98 }}>
            Come worship with us.
          </h2>
          <p style={{ fontSize: 16.5, color: "rgba(245,246,250,.6)", margin: "0 0 32px" }}>Find a CACNA member church near you — onsite or online.</p>
          <div style={{ display: "flex", justifyContent: "center", gap: 16, flexWrap: "wrap" }}>
            <Link href="/zones" style={{ background: "var(--red)", color: "#fff", fontWeight: 700, fontSize: 16, padding: "17px 30px", borderRadius: 999, textDecoration: "none", boxShadow: "0 14px 30px rgba(200,30,58,.4)" }}>Find a Zone →</Link>
            <Link href="/about" style={{ background: "rgba(245,246,250,.1)", color: "var(--cream)", fontWeight: 700, fontSize: 16, padding: "17px 30px", borderRadius: 999, textDecoration: "none", border: "1px solid rgba(245,246,250,.2)" }}>About CACNA</Link>
          </div>
        </Reveal>
      </section>

      <FooterExperience />
    </main>
  );
}
